### ISSUE TITLE
Galaxy fails to fetch the role due to inconsistent versioning

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-ansible-shutdown-env#26]
[root@admin ~]# ansible-galaxy install ovirt.shutdown_env
- downloading role 'shutdown_env', owned by ovirt
 [WARNING]: - ovirt.shutdown_env was NOT installed successfully: Unable to compare role versions (v1.0.0, 1.0.2, 1.0.3) to determine the most recent version due to incompatible
version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by tiraboschi** [comment]
Fixed re-tagging the initial release from v1.0.0 to 1.0.0
